# Generated by Django 4.2.7 on 2023-11-17 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('calibration_frequency', models.IntegerField(default=3)),
                ('calibration_frequency_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months'), ('YEARS', 'Years')], default='MONTHS', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PHReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.DecimalField(decimal_places=3, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StatLogging.measurementdevice')),
            ],
        ),
        migrations.CreateModel(
            name='ECReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('mS/cm', 'Millisiemens per centimeter (mS/cm)'), ('µS/cm', 'Microsiemens per centimeter (µS/cm)'), ('ppm', 'Parts per million (ppm)')], default='mS/cm', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StatLogging.measurementdevice')),
            ],
        ),
    ]
