# Generated by Django 4.2.7 on 2023-11-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatLogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosingguide',
            name='stage_of_growth',
            field=models.CharField(choices=[('Cuttings/Seedlings', 'Cuttings/Seedlings'), ('Vegetative', 'Vegetative'), ('Transitioning', 'Transitioning'), ('Flowering', 'Flowering'), ('Fruiting', 'Fruiting')], max_length=50),
        ),
        migrations.AlterField(
            model_name='grow',
            name='stage',
            field=models.CharField(choices=[('Cuttings/Seedlings', 'Cuttings/Seedlings'), ('Vegetative', 'Vegetative'), ('Transitioning', 'Transitioning'), ('Flowering', 'Flowering'), ('Fruiting', 'Fruiting')], default='Vegetative', max_length=50),
        ),
    ]
